# syntax=docker/dockerfile:1
#
# ScarabHive API server image.
#
#   docker build -t scarabhive .
#   docker run --rm --init -p 127.0.0.1:8000:8000 scarabhive
#
# docker-compose.yml next to this file is the recommended way to run it: it
# mounts config/ from the checkout and keeps data/, logs/ and model caches in
# named volumes.
#
# Why the image looks the way it does:
#
# * The code finds config/, templates/ and static/ relative to the source
#   checkout (two directories above src/agent_system/); data/ and logs/ it
#   resolves partly against the checkout, partly against the working
#   directory. So the checkout is copied to /app,
#   installed in editable mode, and /app is the working directory. A regular
#   (non-editable) install would look for config/ inside site-packages.
# * Dependencies are what pyproject.toml declares: requirements/all.txt
#   (core + every plugin's plugin.toml, generated by
#   scripts/aggregate_plugin_deps.py). That set pulls in PyTorch, so torch and
#   torchaudio are installed first from the CPU-only PyTorch index; from PyPI,
#   torch on Linux x86_64 brings several GB of CUDA libraries.
# * config/secrets.env, config/local.env and config/local.yaml are never part
#   of the image (.dockerignore). The config loader reads them from next to
#   config.yaml when they exist, and a real environment variable always wins
#   over both secrets files.

ARG PYTHON_VERSION=3.12
ARG DEBIAN_RELEASE=trixie

# --------------------------------------------------------------------------
# builder: a virtualenv with every third-party dependency
# --------------------------------------------------------------------------
FROM python:${PYTHON_VERSION}-slim-${DEBIAN_RELEASE} AS builder

# pycairo (via reportlab[pycairo], image_compose plugin) ships wheels for
# Windows only and is compiled here against the cairo headers.
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential pkg-config libcairo2-dev \
    && rm -rf /var/lib/apt/lists/*

ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \
    VIRTUAL_ENV=/opt/venv \
    PATH=/opt/venv/bin:$PATH
RUN python -m venv /opt/venv

# Override for a CUDA build, e.g. https://download.pytorch.org/whl/cu128
# (the container then also needs the NVIDIA container toolkit at runtime).
ARG TORCH_INDEX_URL=https://download.pytorch.org/whl/cpu

COPY requirements/ /tmp/requirements/
# The constraint file pins the torch build installed in the first step, so
# a later requirement can never swap it for the CUDA build from PyPI; a
# conflict fails the build instead.
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip "setuptools>=77" wheel \
    && pip install --index-url "${TORCH_INDEX_URL}" torch torchaudio \
    && pip freeze | grep -iE '^(torch|torchaudio)==' > /tmp/torch-constraints.txt \
    && pip install -c /tmp/torch-constraints.txt -r /tmp/requirements/all.txt

# --------------------------------------------------------------------------
# runtime
# --------------------------------------------------------------------------
FROM python:${PYTHON_VERSION}-slim-${DEBIAN_RELEASE} AS runtime

# libcairo2: runtime library for pycairo.
# EXTRA_APT_PACKAGES: ffmpeg lets pydub convert audio input (FLAC, OGG, ...)
# for the LLM providers. Add tools your agents need in their shell (git,
# openssh-client, ...), or pass an empty value for a smaller image.
ARG EXTRA_APT_PACKAGES="ffmpeg"
RUN apt-get update \
    && apt-get install -y --no-install-recommends libcairo2 ${EXTRA_APT_PACKAGES} \
    && rm -rf /var/lib/apt/lists/*

# Unprivileged user. Match APP_UID/APP_GID to your host user if you bind-mount
# directories the server has to write to.
ARG APP_UID=10001
ARG APP_GID=10001
RUN groupadd --gid "${APP_GID}" scarab \
    && useradd --uid "${APP_UID}" --gid scarab \
       --home-dir /home/scarab --create-home --shell /usr/sbin/nologin scarab

ENV VIRTUAL_ENV=/opt/venv \
    PATH=/opt/venv/bin:$PATH \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUTF8=1 \
    HOST=0.0.0.0 \
    PORT=8000 \
    U2NET_HOME=/home/scarab/.cache/u2net

COPY --from=builder /opt/venv /opt/venv

WORKDIR /app
COPY . /app

# Editable install: registers the package metadata and the console scripts
# (agent-api, agent-cli, ...) while the code stays in /app/src, where it finds
# config/, templates/ and static/. The source tree stays owned by root; the
# bytecode is compiled here because the server cannot write it there.
# data/ and logs/ are the server's writable state (mounted as volumes by
# docker-compose.yml); ~/.cache holds downloaded models (Hugging Face, Chroma,
# and rembg's through U2NET_HOME above -- by default it would use ~/.rembg).
# Known gap: the writer plugins (src/plugins_writer, not part of the open-source
# set) dump debug JSON into src/plugins_writer/writer_pipeline_v4/batch_logs/,
# which the container user cannot write -- a `stop_after=scene_drafts` run
# fails at that dump.
RUN pip install --no-deps --no-build-isolation -e /app \
    && python -m compileall -q -j 0 /app/src \
    && mkdir -p /app/data /app/logs /home/scarab/.cache \
    && chown -R scarab:scarab /app/data /app/logs /home/scarab

USER scarab

EXPOSE 8000

# /api/health is answered without authentication by the shipped
# config/security.yaml (endpoint_security rule "GET /api/health"). Proxies are
# bypassed so an HTTP(S)_PROXY in the environment cannot break the check.
HEALTHCHECK --interval=30s --timeout=10s --start-period=120s --retries=3 \
    CMD ["python", "-c", "import os, urllib.request as u; u.build_opener(u.ProxyHandler({})).open('http://127.0.0.1:' + os.environ.get('PORT', '8000') + '/api/health', timeout=5)"]

# agent-api = agent_system.app:run. It listens on $HOST:$PORT (both set
# above), falling back to network.host/port from config/config.yaml.
CMD ["agent-api"]
