"""Build static/kit/icons.svg -- the UI kit's icon sprite -- from Lucide.

    .venv/Scripts/python.exe src/scripts/build_icon_sprite.py

Only the icons listed in ICONS land in the sprite. To use a new one, add its
Lucide name here and run the script again; the sprite is committed, the UI
never fetches icons at runtime. Lucide is ISC-licensed (static/kit/LICENSE-lucide.txt).
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

LUCIDE_VERSION = "0.460.0"
SOURCE = f"https://cdn.jsdelivr.net/npm/lucide-static@{LUCIDE_VERSION}"
KIT_DIR = Path(__file__).resolve().parents[2] / "static" / "kit"

ICONS = sorted({
    # shell and windows
    "menu", "x", "minus", "maximize-2", "minimize-2", "panel-right", "panel-left",
    "picture-in-picture-2", "external-link", "pin", "pin-off", "search", "command",
    "layout-grid", "grip-vertical", "chevron-down", "chevron-right", "chevron-left",
    "chevron-up", "chevrons-down-up", "ellipsis", "ellipsis-vertical", "arrow-left",
    # theme and account
    "sun", "moon", "monitor", "user", "log-out", "settings", "key-round",
    # actions
    "refresh-cw", "play", "square", "paperclip", "send-horizontal", "plus",
    "trash-2", "pencil", "copy", "check", "download", "upload", "filter",
    "arrow-up", "arrow-down", "rotate-ccw", "save", "eye", "eye-off", "link",
    # debugger (stategraph)
    "pause", "step-forward", "circle-dot", "crosshair",
    # editing (stategraph's graph bar, agent_editor's locked tools)
    "undo-2", "redo-2", "zoom-in", "zoom-out", "rotate-cw", "lock",
    # states
    "info", "triangle-alert", "circle-alert", "circle-check", "circle-x",
    "loader-circle", "clock", "circle-help", "ban",
    # domains
    "bug", "activity", "database", "file-text", "book-open", "library", "layers",
    "brain", "list-todo", "message-square", "messages-square", "users", "shield",
    "cpu", "gauge", "server", "terminal", "scroll-text", "network", "workflow",
    "git-branch", "image", "music", "mic", "wrench", "puzzle", "folder", "history",
    "chart-column", "lightbulb", "graduation-cap", "gamepad-2", "clapperboard",
    "notebook-pen", "hard-drive", "plug", "globe",
})

_BODY = re.compile(r"<svg[^>]*>(.*)</svg>", re.DOTALL)


def fetch(path: str) -> str:
    with urllib.request.urlopen(f"{SOURCE}/{path}", timeout=30) as response:
        return response.read().decode("utf-8")


def main() -> int:
    symbols = []
    for name in ICONS:
        body = _BODY.search(fetch(f"icons/{name}.svg"))
        if not body:
            print(f"no <svg> body in {name}.svg", file=sys.stderr)
            return 1
        inner = "".join(line.strip() for line in body.group(1).splitlines())
        symbols.append(f'<symbol id="{name}" viewBox="0 0 24 24">{inner}</symbol>')

    sprite = (f"<!-- Lucide {LUCIDE_VERSION} (ISC), generated by src/scripts/build_icon_sprite.py -->\n"
              '<svg xmlns="http://www.w3.org/2000/svg">\n' + "\n".join(symbols) + "\n</svg>\n")
    (KIT_DIR / "icons.svg").write_text(sprite, encoding="utf-8")
    (KIT_DIR / "LICENSE-lucide.txt").write_text(fetch("LICENSE"), encoding="utf-8")
    print(f"{len(symbols)} icons -> {KIT_DIR / 'icons.svg'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
