"""Invalidation of provider-side reasoning artifacts on history mutation.

THE INVARIANT
=============
``reasoning_details`` blocks (OpenAI encrypted reasoning items, Gemini thought
signatures via OpenRouter) are integrity-protected artifacts over the EXACT
conversation history that produced them:

- OpenAI reasoning models chain their encrypted items — every item is verified
  against the full sequence of prior items ("the entire sequence of consecutive
  reasoning blocks must match the outputs generated by the model during the
  original request", OpenRouter docs). Dropping or altering ANY earlier part
  fails verification: HTTP 400 "The encrypted content for item rs_… could not
  be verified".
- Gemini validates the thought signature of the CURRENT tool-call round-trip.

Therefore: any process that mutates persisted conversation history AFTER
assistant turns were generated — compaction (content swapped for variable
refs), media/tool-result eviction, summarization replacing whole spans —
silently invalidates these artifacts. The failure then surfaces LATER, deep
into a run, when the next LLM call round-trips the now-inconsistent chain.

THE RULE
========
Every code path that mutates history MUST call
:func:`invalidate_reasoning_artifacts` on the message list afterwards.

What it does (provider-agnostic — callers don't know which model runs):

1. Strips ``reasoning_details`` from every assistant message EXCEPT the most
   recent one. The most recent may belong to a still-open tool round-trip whose
   Gemini thought signature is REQUIRED on the very next request (stripping it
   risks MALFORMED_FUNCTION_CALL).
2. Flags the most recent assistant message with ``_rd_orphaned: True`` —
   "your predecessors were removed; your chain is broken".

The provider-aware side lives in the LLM client (config-driven
``reasoning_details_mode``, no model-name sniffing):

- ``keep_all`` (OpenAI reasoning chains): an ``_rd_orphaned`` message gets its
  ``reasoning_details`` stripped per-request too — completing a clean chain
  reset. The model re-reasons once; every item generated afterwards forms a
  fresh, internally consistent chain that verifies again.
- ``keep_last`` (Gemini): the flag is ignored — the latest signature is kept
  (needed for the open round-trip; older ones were never round-tripped anyway).

``_rd_orphaned`` never reaches a provider: the client pops it in its
message post-processing right before the payload is built.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)

#: Flag set on the most recent assistant message when its reasoning-chain
#: predecessors were removed by a history mutation. Read (and honored
#: per reasoning_details_mode) by the LLM client, which also strips the flag
#: from outgoing payloads. No leading underscore: it doubles as a declared
#: pydantic field on ChatMessage (pydantic forbids underscore-prefixed field
#: names), so it survives model_dump / session round-trips.
RD_ORPHANED_FLAG = "rd_orphaned"


def _get(msg: Any, key: str, default: Any = None) -> Any:
    """Field access that works for both dict messages and message objects."""
    if isinstance(msg, dict):
        return msg.get(key, default)
    return getattr(msg, key, default)


def _pop(msg: Any, key: str) -> Any:
    if isinstance(msg, dict):
        return msg.pop(key, None)
    val = getattr(msg, key, None)
    if val is not None:
        # Objects (e.g. pydantic ChatMessage): set to None instead of delattr.
        # pydantic v2 tolerates delattr but leaves the instance broken — the
        # attribute then raises AttributeError on access instead of returning
        # the field default.
        try:
            setattr(msg, key, None)
        except Exception:
            pass
    return val


def _set(msg: Any, key: str, value: Any) -> None:
    if isinstance(msg, dict):
        msg[key] = value
    else:
        try:
            setattr(msg, key, value)
        except Exception:
            pass  # frozen/slotted message objects: flag is best-effort


def thinking_text_from_details(details: Any) -> str:
    """The readable thinking text carried inside ``reasoning_details``.

    Two shapes exist, and both occur in stored sessions:

    * flat blocks — ``{"type": "reasoning.text", "text": ...}``, and
      ``reasoning.summary`` which keeps its text in ``summary`` instead.
      Streamed fragments are merged per index by the client, so a block
      arriving here is already whole: measured over 95.399 stored sessions,
      separate blocks are separate SECTIONS, each with its own ``**heading**``
      and ending on punctuation — in all 702 multi-block messages at least one
      block ends without trailing whitespace. They are therefore joined like
      paragraphs, not glued: gluing produced
      ``...proper continuity.**Evaluating story inconsistencies**``.
    * a verbatim replay block — ``reasoning.responses_items`` whose ``items``
      are the provider's raw output items; a reasoning item keeps its text in
      ``content[]`` (raw thinking) or ``summary[]`` (condensed).

    ``data`` is never read: that is the encrypted payload for the round-trip,
    not text.

    Accepts a list of blocks or the streaming accumulator (index -> block).
    """
    if isinstance(details, dict):
        details = [details[index] for index in sorted(details)]
    fragments: list[str] = []
    items_texts: list[str] = []
    for block in details or []:
        if not isinstance(block, dict):
            continue
        for item in block.get("items") or ():
            if not isinstance(item, dict) or item.get("type") != "reasoning":
                continue
            for field in ("content", "summary"):
                for part in item.get(field) or ():
                    if (isinstance(part, dict)
                            and isinstance(part.get("text"), str)
                            and part["text"].strip()):
                        items_texts.append(part["text"])
        value = block.get("text") or block.get("summary")
        if isinstance(value, str) and value.strip():
            fragments.append(value)
    return "\n\n".join(fragments + items_texts)


def thinking_text(msg: Any) -> str:
    """The thinking text of one message, wherever it currently lives.

    The text is stored ONCE: on the message as ``reasoning_content`` when the
    provider sent it on its own, or inside ``reasoning_details`` when that
    artifact has to be kept verbatim anyway. Storing both doubled the session
    size of every reasoning run for no gain, so readers ask here instead of
    picking one field.
    """
    own = _get(msg, "reasoning_content")
    if isinstance(own, str) and own.strip():
        return own
    return thinking_text_from_details(_get(msg, "reasoning_details"))


def _keep_thinking_text(msg: Any) -> None:
    """Move the thinking text onto the message before its artifacts are lost.

    Used where the artifact is discarded for a reason that has nothing to do
    with size — a model switch or a chain repair. There the thinking would be
    lost for good, and that is the fallback case worth keeping.

    NOT used by :func:`invalidate_reasoning_artifacts`. That one runs after
    compaction and summarization, which exist BECAUSE the context is too
    large; writing the thinking back would undo part of the very saving they
    just made, permanently and per message (measured over stored sessions:
    median 5.034 characters, p90 11.946, max 373.776). A durable archive for
    reasoning belongs beside the session, not inside it.

    Never overwrites an existing value, and stays silent when there is nothing
    to rescue.
    """
    if _get(msg, "reasoning_content"):
        return
    text = thinking_text_from_details(_get(msg, "reasoning_details"))
    if text:
        _set(msg, "reasoning_content", text)


def strip_reasoning_artifacts_containing(messages: list, item_id: str) -> int:
    """Remove reasoning artifacts of the message(s) carrying block *item_id*.

    Surgical variant of :func:`strip_all_reasoning_artifacts` for the
    "encrypted content for item rs_… could not be verified" 400: the provider
    names ONE defective item — empirically (OpenRouter bridge, assistant turns
    with multiple parallel tool_calls) every OTHER item of the chain still
    verifies once the named one is gone. Dropping only the affected message's
    ``reasoning_details`` preserves the rest of the chain, the prompt cache and
    the model's reasoning continuity.

    The whole ``reasoning_details`` list of a matching message is removed (not
    just the matching block): sibling blocks like ``reasoning.summary`` carry
    no id of their own and are useless without their encrypted twin.

    Works on dicts and message objects. Returns number of messages touched.
    """
    touched = 0
    for msg in messages:
        if _get(msg, "role") != "assistant":
            continue
        blocks = _get(msg, "reasoning_details") or []
        if any(isinstance(b, dict) and b.get("id") == item_id for b in blocks):
            _keep_thinking_text(msg)
            _pop(msg, "reasoning_details")
            _pop(msg, RD_ORPHANED_FLAG)
            touched += 1
    if touched:
        logger.info(
            "Reasoning artifacts stripped from %d message(s) carrying "
            "defective item %s (rest of the chain preserved)",
            touched, item_id,
        )
    return touched


def strip_all_reasoning_artifacts(messages: list) -> int:
    """Remove ALL provider reasoning artifacts from *messages* — full reset.

    Use when the artifacts are invalid beyond the reach of the soft reset in
    :func:`invalidate_reasoning_artifacts` (which keeps the latest message's
    artifact for an open same-model tool round-trip):

    - **Mid-run model switch** (fallback, fallback-recovery, escalation): the
      old model's artifacts are useless or harmful to the new model in BOTH
      directions (OpenAI can't verify Gemini blocks and vice versa). The open
      round-trip belongs to the OLD model, so even the latest artifact must go
      — for the new model this is simply a fresh start.
    - **Poisoned session healing** after a provider rejected the chain
      (HTTP 400 "encrypted content … could not be verified"): stripping only
      the serialized request copy re-triggers the same 400 every turn, because
      the session still carries the broken chain. Strip the ORIGINAL message
      objects so the healing persists with the session.

    Also clears any ``rd_orphaned`` flags (obsolete once nothing is left).
    Works on dicts and message objects. Returns number of messages touched.
    """
    touched = 0
    for msg in messages:
        if _get(msg, "role") != "assistant":
            continue
        _keep_thinking_text(msg)
        had = _pop(msg, "reasoning_details") is not None
        had_flag = _pop(msg, RD_ORPHANED_FLAG) is not None
        if had or had_flag:
            touched += 1
    if touched:
        logger.info(
            "All reasoning artifacts stripped from %d message(s) "
            "(model switch or poisoned-chain healing; chain restarts fresh)",
            touched,
        )
    return touched


def invalidate_reasoning_artifacts(messages: list, start: int = 0) -> int:
    """Invalidate provider reasoning artifacts after a history mutation.

    Call this AFTER any in-place mutation of persisted conversation history
    (compaction, summarization, eviction). Strips ``reasoning_details`` from
    all assistant messages except the most recent, and flags the most recent
    with ``_rd_orphaned`` so the LLM client can complete the reset for
    chain-based providers (reasoning_details_mode="keep_all").

    Works on both dict-shaped messages and message objects.

    Args:
        messages: the (already mutated) conversation history, oldest first.
        start: index of the first message the mutation changed. Assistant
            turns before it came from a history that is unchanged, so their
            artifacts stay — stripping them would rewrite every replayed turn
            and move the prompt-cache break to the front of the conversation.

    Returns:
        Number of messages whose reasoning artifacts were stripped or flagged.
        0 means the history carried no reasoning artifacts — nothing to do.
    """
    touched = 0
    last_assistant_idx = -1
    for i, msg in enumerate(messages):
        if _get(msg, "role") == "assistant":
            last_assistant_idx = i

    if last_assistant_idx < 0:
        return 0

    for i, msg in enumerate(messages):
        if i < start or _get(msg, "role") != "assistant":
            continue
        if i == last_assistant_idx:
            if _get(msg, "reasoning_details"):
                _set(msg, RD_ORPHANED_FLAG, True)
                touched += 1
            continue
        # No rescue here on purpose: this runs after a compaction, whose job
        # is to make the history smaller. See _keep_thinking_text.
        if _pop(msg, "reasoning_details") is not None:
            touched += 1

    if touched:
        logger.info(
            "Reasoning artifacts invalidated after history mutation: "
            "%d message(s) stripped/flagged (chain will rebuild fresh)",
            touched,
        )
    return touched
