"""Aggregate framework-core + per-plugin Python requirements.

Each plugin declares its own pip requirements in its ``plugin.toml``
(``[plugin] dependencies = [...]``) — or, during the migration, in the legacy
``plugin.toml``. This script merges ``requirements/core.txt`` (framework deps
not owned by any single plugin) with every public plugin's declared
requirements and writes the deduplicated result to ``requirements/all.txt``.
Further plugin roots next to it (``src/plugins_<name>/``) are not part of the
open-source release; what they need beyond ``all.txt`` goes to
``requirements/private.txt``, written only where such roots exist. The root
``pyproject.toml`` reads both via ``[tool.setuptools.dynamic]`` (setuptools
skips a missing file), so a private checkout installs everything and a public
one only its own. That keeps plugin-owned dependencies OUT of the root pyproject.

Run after changing any plugin's dependencies (or core.txt):

    python scripts/aggregate_plugin_deps.py

A drift-guard test (tests/pluginsystem/test_plugin_deps_aggregation.py) fails if
either file is stale relative to the sources.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from agent_system.plugins.plugin_manifest import plugin_pip_dependencies  # noqa: E402

PLUGIN_DIRS = [
    ROOT / "src" / "plugins",
]
#: Every other plugin root of this checkout (config/plugins.yaml: src/plugins*).
PRIVATE_PLUGIN_DIRS = sorted(d for d in (ROOT / "src").glob("plugins_*")
                             if d.is_dir() and d.name.isidentifier())
CORE_FILE = ROOT / "requirements" / "core.txt"
OUT_FILE = ROOT / "requirements" / "all.txt"
PRIVATE_OUT_FILE = ROOT / "requirements" / "private.txt"

HEADER = (
    "# GENERATED by scripts/aggregate_plugin_deps.py — DO NOT EDIT BY HAND.\n"
    "# Sources: requirements/core.txt + every plugin's plugin.toml\n"
    "# 'dependencies'. Re-run the script after changing any plugin's deps;\n"
    "# the root pyproject.toml reads this file via [tool.setuptools.dynamic].\n"
)
PRIVATE_HEADER = (
    "# GENERATED by scripts/aggregate_plugin_deps.py — DO NOT EDIT BY HAND.\n"
    "# What the plugin roots besides src/plugins need beyond all.txt.\n"
    "# Not part of the open-source release; pyproject.toml reads it when present.\n"
)


def _read_requirements_file(path: Path) -> list[str]:
    """Non-empty, non-comment lines of a requirements file."""
    if not path.exists():
        return []
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            out.append(stripped)
    return out


def _key(spec: str) -> str:
    return spec.lower().replace(" ", "")


def _plugin_specs(roots: list[Path]) -> list[str]:
    out: list[str] = []
    for plugin_dir in roots:
        if not plugin_dir.exists():
            continue
        for d in sorted(plugin_dir.iterdir()):
            if not d.is_dir() or d.name.startswith((".", "_")):
                continue
            out.extend(plugin_pip_dependencies(d))
    return out


def _dedup(specs: list[str]) -> list[str]:
    """Dedup is by exact normalized spec (first occurrence wins); two DIFFERENT
    specs for the same package are both kept and left to pip's resolver — a
    conflict is a real problem the author should see, not silently drop."""
    seen: dict[str, str] = {}
    for spec in specs:
        seen.setdefault(_key(spec), spec)
    return sorted(seen.values(), key=str.lower)


def collect_requirements() -> list[str]:
    """Merged, deduplicated requirement specs (core + public plugins), sorted."""
    return _dedup(_read_requirements_file(CORE_FILE) + _plugin_specs(PLUGIN_DIRS))


def collect_private_requirements() -> list[str]:
    """What the private roots need that all.txt does not already carry."""
    public = {_key(s) for s in collect_requirements()}
    return [s for s in _dedup(_plugin_specs(PRIVATE_PLUGIN_DIRS)) if _key(s) not in public]


def has_private_roots() -> bool:
    return any(d.exists() for d in PRIVATE_PLUGIN_DIRS)


def render() -> str:
    return HEADER + "\n".join(collect_requirements()) + "\n"


def render_private() -> str:
    return PRIVATE_HEADER + "\n".join(collect_private_requirements()) + "\n"


def main() -> int:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(ROOT)} "
          f"({len(collect_requirements())} requirements)")
    if has_private_roots():
        PRIVATE_OUT_FILE.write_text(render_private(), encoding="utf-8")
        print(f"Wrote {PRIVATE_OUT_FILE.relative_to(ROOT)} "
              f"({len(collect_private_requirements())} requirements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
