"""Aggregate framework-core + per-plugin Python requirements into one file.

Each plugin declares its own pip requirements in its ``plugin.toml``
(``[plugin] dependencies = [...]``) — or, during the migration, in the legacy
``plugin.yaml``. This script merges ``requirements/core.txt`` (framework deps
not owned by any single plugin) with every plugin's declared requirements and
writes the deduplicated result to ``requirements/all.txt``, which the root
``pyproject.toml`` reads via ``[tool.setuptools.dynamic]``. That keeps
plugin-owned dependencies OUT of the root pyproject.

Run after changing any plugin's dependencies (or core.txt):

    python scripts/aggregate_plugin_deps.py

A drift-guard test (tests/pluginsystem/test_plugin_deps_aggregation.py) fails if
``requirements/all.txt`` is stale relative to the sources.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from agent_system.plugins.plugin_manifest import plugin_pip_dependencies  # noqa: E402

PLUGIN_DIRS = [ROOT / "src" / "plugins", ROOT / "src" / "plugins_writer"]
CORE_FILE = ROOT / "requirements" / "core.txt"
OUT_FILE = ROOT / "requirements" / "all.txt"

HEADER = (
    "# GENERATED by scripts/aggregate_plugin_deps.py — DO NOT EDIT BY HAND.\n"
    "# Sources: requirements/core.txt + every plugin's plugin.toml/plugin.yaml\n"
    "# 'dependencies'. Re-run the script after changing any plugin's deps;\n"
    "# the root pyproject.toml reads this file via [tool.setuptools.dynamic].\n"
)


def _read_requirements_file(path: Path) -> list[str]:
    """Non-empty, non-comment lines of a requirements file."""
    if not path.exists():
        return []
    out: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            out.append(stripped)
    return out


def collect_requirements() -> list[str]:
    """Merged, deduplicated requirement specs (core + all plugins), sorted.

    Dedup is by exact normalized spec (first occurrence wins); two DIFFERENT
    specs for the same package are both kept and left to pip's resolver — a
    conflict is a real problem the author should see, not silently drop.
    """
    seen: dict[str, str] = {}

    def add(spec: str) -> None:
        key = spec.lower().replace(" ", "")
        seen.setdefault(key, spec)

    for spec in _read_requirements_file(CORE_FILE):
        add(spec)

    for plugin_dir in PLUGIN_DIRS:
        if not plugin_dir.exists():
            continue
        for d in sorted(plugin_dir.iterdir()):
            if not d.is_dir() or d.name.startswith((".", "_")):
                continue
            for spec in plugin_pip_dependencies(d):
                add(spec)

    return sorted(seen.values(), key=str.lower)


def render() -> str:
    return HEADER + "\n".join(collect_requirements()) + "\n"


def main() -> int:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    content = render()
    OUT_FILE.write_text(content, encoding="utf-8")
    print(f"Wrote {OUT_FILE.relative_to(ROOT)} "
          f"({len(collect_requirements())} requirements)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
