# simple chat agent
plugins:
  servers:
    chat_agent:
      type: basic_agent
      enabled: true
      description: "Simple chat agent"
      
      agent_config:
        llm_profile: chat
        max_steps: 30
                
        hooks:
          enabled: true
          overrides:
            markdown_formatter.format_markdown_output:
              enabled: true
      
      metadata:
        visibility: "both"
        tags:
          - chat
          - simple
          - assistant